# Generated by Django 5.1.6 on 2025-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="code",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
