# Generated by Django 5.1.6 on 2025-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_token",
            field=models.TextField(blank=True, default=""),
        ),
    ]
