# Generated by Django 5.1.6 on 2025-03-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
